db:
  build: Dockers/db
  ports:
    - 5433:5432
es:
  build: Dockers/es
  ports:
    - 9203:9200
redis:
  image: redis:2.8
  ports:
    - 6373:6379
selenium:
  image: selenium/standalone-chrome
  ports:
    - 4443:4444
web:
  build: .
  command: python manage.py runserver 0:8000
  environment:
    - DJANGO_LIVE_TEST_SERVER_ADDRESS=0:8081
  volumes:
    - .:/home/docker/hellolily
  ports:
    - 8003:8000
    - 8083:8081
  links:
    # Define all containers for easy running of development setup.
    - db
    - es
    - rabbit
    - redis
    - beat
    - worker1
    - worker2
    - selenium
rabbit:
  build: Dockers/rabbit
beat:
  build: .
  command: celery worker -B --app=lily.celery --loglevel=info -Q celery -n beat.%h -c 1
  volumes: [".:/home/docker/hellolily"]
  links: [rabbit, db, redis, es]
worker1:
  build: .
  command: celery worker --loglevel=info --app=lily.celery -Q queue1 -n worker1.%h -c 12 -P eventlet
  volumes: [".:/home/docker/hellolily"]
  links: [rabbit, db, redis, es]
worker2:
  build: .
  command: celery worker --loglevel=info --app=lily.celery -Q queue2 -n worker2.%h -c 12 -P eventlet
  volumes: [".:/home/docker/hellolily"]
  links: [rabbit, db, redis, es]
