version: '2'

networks:
  internal:
  # external:  # Reserved for load balancer / proxy.

services:
  rabbit:
    image: rabbitmq:3.6-management  # Use latest version of 3.6 with management plugin enabled.
    networks:
      internal:
    ports:
      - "5672"
    logging:
      driver: "none"

  redis:
    image: redis:2.8  # Use latest version of 2.8.
    networks:
      internal:
    ports:
      - "6373:6379"
    logging:
      driver: "none"

  db:
    image: postgres:9.5-alpine
    networks:
      internal:
    environment:
      - POSTGRES_USER=hellolily
    ports:
      - "5433:5432"
    logging:
      driver: "none"

  es_old:
    image: elasticsearch:1.7-alpine  # Use latest version of 1.7.
    networks:
      internal:
    ports:
      - "9200:9200"
      - "9300:9300"
    logging:
      driver: "none"

  app:
    image: "hellolily/hellolily:latest"
    command: "/bin/true"
    networks:
      - internal
    environment:
      - PYTHONUNBUFFERED=true
      - DJANGO_SETTINGS_MODULE=lily.settings.settings
      - DEBUG=1
      - SECRET_KEY=abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmn
      - DATABASE_URL=postgres://hellolily:@db/hellolily
      - MULTI_TENANT=1
      - TLDEXTRACT_CACHE=./.tld_set
      - DISABLE_DATADOG_AGENT=true
      - DATADOG_TRACE_ENABLED=false
    volumes:
      - .:/home/docker/hellolily
    cap_drop:
      - ALL

  web:
    extends: app
    command: bash -c "Dockers/wait-for db:5432 && python manage.py runserver 0:8000"
    networks:
      - internal
    depends_on:
      - rabbit
      - redis
      - db
      - es_old
    ports:
      - "8080:8000"
      - "8083:8081"

  flower:
    extends: app
    command: bash -c "Dockers/wait-for rabbit:5672 && flower --app=lily.celery"
    depends_on:
      - db
      - rabbit
    ports:
      - "5555"

  beat:
    extends: app
    command: bash -c "Dockers/wait-for rabbit:5672 && celery worker -B --app=lily.celery --loglevel=info -Q celery -n beat.%h -c 1"
    depends_on:
      - rabbit
      - redis
      - db
      - es_old

  worker1:
    extends: app
    command: bash -c "Dockers/wait-for rabbit:5672 && celery worker --loglevel=info --app=lily.celery -Q email_async_tasks -n worker1.%h -c 12 -P eventlet"
    depends_on:
      - rabbit
      - redis
      - db
      - es_old

  worker2:
    extends: app
    command: bash -c "Dockers/wait-for rabbit:5672 && celery worker --loglevel=info --app=lily.celery -Q email_scheduled_tasks,email_first_sync,other_tasks -n worker2.%h -c 12 -P eventlet"
    depends_on:
      - rabbit
      - redis
      - db
      - es_old
